const fs = require('fs')
const reg = require('../../electron/tool-registry.mts')
const p = 'tests/tool-registry.test.cjs'
let s = fs.readFileSync(p, 'utf8')
function rep(a, b) { if (s.split(a).length !== 2) throw new Error('count ' + (s.split(a).length - 1) + ': ' + a.slice(0, 70)); s = s.replace(a, () => b) }
const oldRead = "capability_read {id}: full instructions of one skill. capability_feedback"
const oldInstall = s.slice(s.indexOf('capability_install {name,description'), s.indexOf('Verify helper scripts before saving a skill.') + 'Verify helper scripts before saving a skill.'.length)
const spec = n => reg.tool(n)
const esc = t => t.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
rep(oldRead, `capability_read {id}: ${esc(spec('capability_read').blurb)} capability_feedback`)
rep(oldInstall, esc(`capability_install ${spec('capability_install').signature}: ${spec('capability_install').blurb}`))
rep("capability_install: { name: string, instructions: string, description: string, whenToUse: optional(string), id: optional(string), scope: optional({ type: 'string', enum: ['project', 'global'] }), source: optional(string) },",
  "capability_install: {\n      name: optional(string), instructions: optional(string), description: optional(string), whenToUse: optional(string), id: optional(string), scope: optional({ type: 'string', enum: ['project', 'global'] }), source: optional(string),\n      files: optional({ type: 'array', items: object({ path: string, content: string }) }), removeFiles: optional(strings), fromDir: optional(string),\n      params: optional({ type: 'array', items: object({ key: string, label: string, type: { type: 'string', enum: ['text', 'url', 'number', 'seconds', 'boolean'] }, default: { anyOf: [string, number, boolean] }, hint: optional(string) }) }),\n      triggers: optional({ type: 'array', items: object({ on: { type: 'string', enum: ['task-completed'] }, show: string }) }),\n      commands: optional({ type: 'array', items: object({ name: string, run: string, description: optional(string) }) }),\n    },")
rep("  assert.match(validate('capability_install', { name: 'n', instructions: ' ', description: 'd' }).error, /name and instructions/)\n",
  "  assert.match(validate('capability_install', { name: 'n', instructions: ' ', description: 'd' }).error, /name and instructions/)\n  assert.equal(validate('capability_install', { fromDir: '/tmp/pack' }).ok, true, 'a folder with a skill.json needs no name')\n  assert.equal(validate('capability_install', { id: 'known', files: [{ path: 'a.txt', content: 'x' }] }).ok, true, 'an existing skill keeps its text')\n  assert.match(validate('capability_install', { name: 'n', instructions: 'i', files: [{ path: 'a.txt' }] }).error, /files\\[0\\]\\.content is required/)\n  assert.match(validate('capability_install', { name: 'n', instructions: 'i', params: [{ key: 'k', label: 'L', type: 'color', default: 'x' }] }).error, /type must be one of/)\n  assert.match(validate('capability_install', { name: 'n', instructions: 'i', triggers: [{ on: 'never', show: 'p.html' }] }).error, /on must be one of/)\n  assert.equal(validate('capability_install', { name: 'n', instructions: 'i', params: [{ key: 'k', label: 'L', type: 'number', default: 3, hint: null }], commands: [{ name: 'go', run: 'node go.js' }] }).ok, true, 'nested optional fields may be null or missing')\n")
fs.writeFileSync(p, s)
