// Isolated copies of a workspace (electron/agent-worktree.mts): a copy starts from the parent's current state without
// touching it, a finished helper's changes merge into the target file by file (conflicts leave the target alone), nested
// copies work, and removing a copy never follows its links. Everything runs against real temporary git repositories.
// The tests are spread over agent-worktree*.test.cjs, which run side by side (the fixtures are in helpers-worktree.cjs).
// This part makes copies: of a parent with uncommitted work, of a repository without commits, of a folder below the
// repository's top, several at once and without the user's hooks; a workspace outside any work tree is refused.
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const worktree = require('../electron/agent-worktree.mts')
const { git, folder, put, read, repo, copyOf, paths } = require('./helpers-worktree.cjs')

test('a copy starts from the parent\'s current state and leaves its HEAD, index and files untouched', async t => {
  const dir = repo(t)
  put(dir, { 'a.txt': 'one\nTWO\nthree\n', 'new.txt': 'untracked\n', 'staged.txt': 'staged\n' })
  git(dir, 'add', 'staged.txt')
  put(dir, { 'node_modules/pkg.js': 'module\n' })
  const state = () => ({ head: git(dir, 'rev-parse', 'HEAD'), status: git(dir, 'status', '--porcelain', '-uall'), staged: git(dir, 'diff', '--cached', '--name-status'), refs: git(dir, 'for-each-ref'), index: fs.readFileSync(path.join(dir, '.git', 'index')).toString('hex') })
  const before = state()
  const { copy, root } = await copyOf(t, dir)
  assert.deepEqual(state(), before, 'the parent\'s HEAD, refs, index and working tree are as they were')
  assert.equal(read(copy.workspace, 'a.txt'), 'one\nTWO\nthree\n', 'a change that is not committed')
  assert.equal(read(copy.workspace, 'staged.txt'), 'staged\n', 'a staged new file')
  assert.equal(read(copy.workspace, 'new.txt'), 'untracked\n', 'an untracked file that git does not ignore')
  assert.equal(git(dir, 'rev-parse', `${copy.startBase}^`), before.head, 'the snapshot commit sits on top of HEAD')
  assert.equal(copy.workspace, copy.dir)
  assert.equal(copy.target, dir)
  assert.ok(copy.dir.startsWith(`${root}${path.sep}`), 'the copy lives under the worktrees folder, never inside the parent')
  const linked = path.join(copy.dir, 'node_modules')
  assert.deepEqual(copy.links, [linked])
  assert.ok(fs.lstatSync(linked).isSymbolicLink(), 'the ignored node_modules is linked, not copied')
  assert.equal(read(linked, 'pkg.js'), 'module\n')
  const removed = await worktree.removeCopy(copy, root, 'run-test')
  assert.deepEqual([removed.removed, removed.patch], [true, null], 'nothing was left unmerged, so there is no patch')
  assert.equal(fs.existsSync(copy.dir), false)
  assert.equal(read(dir, 'node_modules/pkg.js'), 'module\n', 'removing the link did not touch the folder it pointed to')
  assert.equal(git(dir, 'worktree', 'list').split('\n').length, 1, 'git no longer lists the copy')
  assert.deepEqual(fs.readdirSync(root), [], 'the run folder went away with its last copy')
})

test('a workspace outside any git work tree is refused and leaves nothing behind', async t => {
  const plain = folder(t, 'plain'), root = folder(t, 'root')
  const refused = await worktree.createCopy({ source: plain, kind: 'worktree', root, runId: 'run-test', agentId: 'agent-plain' })
  assert.equal(refused.ok, false)
  assert.match(refused.detail, /is not inside a git work tree/)
  const missing = await worktree.createCopy({ source: path.join(plain, 'nope'), kind: 'worktree', root, runId: 'run-test', agentId: 'agent-missing' })
  assert.equal(missing.ok, false)
  assert.match(missing.detail, /not a folder that exists/)
  assert.deepEqual(fs.readdirSync(root), [])
})

test('a repository without commits can be copied and merged', async t => {
  const dir = repo(t, { 'a.txt': 'first\n' }, { commit: false })
  const { copy } = await copyOf(t, dir)
  assert.equal(read(copy.workspace, 'a.txt'), 'first\n')
  assert.throws(() => git(dir, 'rev-parse', '--verify', '-q', 'HEAD'), 'the snapshot did not create a HEAD in the parent')
  put(copy.workspace, { 'a.txt': 'second\n', 'b.txt': 'b\n' })
  const result = await worktree.mergeCopy(copy)
  assert.deepEqual(paths(result.merged), ['a.txt', 'b.txt'])
  assert.equal(read(dir, 'a.txt'), 'second\n')
})

test('a workspace below the repository top gets its place in the copy, and only its own files merge', async t => {
  const dir = repo(t, { 'pkg/a.txt': 'a\n', 'top.txt': 't\n' })
  put(dir, { 'pkg/node_modules/m.js': 'm' })
  const { copy } = await copyOf(t, path.join(dir, 'pkg'))
  assert.deepEqual([copy.relPrefix, copy.workspace, copy.target], ['pkg', path.join(copy.dir, 'pkg'), path.join(dir, 'pkg')])
  assert.deepEqual(copy.links, [path.join(copy.dir, 'pkg', 'node_modules')], 'the workspace\'s own node_modules is linked')
  put(copy.workspace, { 'a.txt': 'a changed\n', 'new.txt': 'n\n' })
  put(copy.dir, { 'top.txt': 'changed outside the workspace\n' })
  const result = await worktree.mergeCopy(copy)
  assert.deepEqual(paths(result.merged), ['pkg/a.txt', 'pkg/new.txt'])
  assert.equal(read(dir, 'top.txt'), 't\n', 'a file outside the helper\'s workspace stays as it is')
})

test('copies made at once and merges into one target are serialized, and the run\'s meta.json lists every copy', async t => {
  const dir = repo(t, { 'a.txt': 'l1\nl2\nl3\nl4\nl5\n' })
  const root = folder(t, 'root')
  const [one, two] = await Promise.all([copyOf(t, dir, { root }), copyOf(t, dir, { root })])
  const runFolders = fs.readdirSync(root)
  assert.equal(runFolders.length, 1)
  const meta = JSON.parse(fs.readFileSync(path.join(root, runFolders[0], 'meta.json'), 'utf8'))
  assert.deepEqual([meta.version, meta.pid, meta.copies.length], [1, process.pid, 2])
  put(one.copy.workspace, { 'a.txt': 'H1\nl2\nl3\nl4\nl5\n', 'one.txt': '1\n' })
  put(two.copy.workspace, { 'a.txt': 'l1\nl2\nl3\nl4\nH5\n', 'two.txt': '2\n' })
  const [first, second] = await Promise.all([worktree.mergeCopy(one.copy), worktree.mergeCopy(two.copy)])
  assert.deepEqual([first.conflicts, second.conflicts], [[], []])
  assert.equal(read(dir, 'a.txt'), 'H1\nl2\nl3\nl4\nH5\n', 'both helpers\' edits of one file landed')
  assert.deepEqual([read(dir, 'one.txt'), read(dir, 'two.txt')], ['1\n', '2\n'])
  await Promise.all([worktree.removeCopy(one.copy, root), worktree.removeCopy(two.copy, root)])
  assert.deepEqual(fs.readdirSync(root), [])
})

test('a hook of the user\'s repository does not run when a copy is made', async t => {
  const dir = repo(t)
  const marker = path.join(folder(t, 'marker'), 'ran.txt')
  const hook = path.join(dir, '.git', 'hooks', 'post-checkout')
  fs.writeFileSync(hook, `#!/bin/sh\necho ran > "${marker.replace(/\\/g, '/')}"\n`, { mode: 0o755 })
  const control = path.join(folder(t, 'control'), 'wt')
  git(dir, 'worktree', 'add', '--detach', control, 'HEAD')
  if (!fs.existsSync(marker)) return t.skip('hooks do not run in this environment, so the check would prove nothing')
  fs.rmSync(marker)
  const { copy } = await copyOf(t, dir)
  assert.equal(fs.existsSync(marker), false)
  assert.ok(fs.existsSync(path.join(copy.dir, 'a.txt')))
})
