// Isolated copies of a workspace (electron/agent-worktree.mts): a copy starts from the parent's current state without
// touching it, a finished helper's changes merge into the target file by file (conflicts leave the target alone), nested
// copies work, and removing a copy never follows its links. Everything runs against real temporary git repositories.
// The tests are spread over agent-worktree*.test.cjs, which run side by side (the fixtures are in helpers-worktree.cjs).
// This part follows a copy to its end: a copy of a copy, removal with a patch for what never merged, links that are never
// followed, and the sweep at start.
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const worktree = require('../electron/agent-worktree.mts')
const { git, folder, put, read, repo, copyOf, paths } = require('./helpers-worktree.cjs')

test('a copy of a copy merges into its parent\'s copy first, and only that reaches the original', async t => {
  const dir = repo(t, { 'a.txt': 'a\n' })
  const { copy: parent, root } = await copyOf(t, dir)
  put(parent.workspace, { 'mine.txt': 'parent\n' })
  const { copy: child } = await copyOf(t, parent.workspace, { root, origin: parent.origin })
  assert.equal(child.sourceTop, parent.dir)
  assert.equal(child.origin, dir, 'git\'s bookkeeping stays with the original repository')
  assert.equal(read(child.workspace, 'mine.txt'), 'parent\n', 'the child starts from the parent\'s uncommitted state')
  put(child.workspace, { 'deep.txt': 'child\n' })
  const inner = await worktree.mergeCopy(child)
  assert.deepEqual(paths(inner.merged), ['deep.txt'])
  assert.equal(read(parent.workspace, 'deep.txt'), 'child\n')
  assert.equal(fs.existsSync(path.join(dir, 'deep.txt')), false, 'the original is not touched yet')
  const outer = await worktree.mergeCopy(parent)
  assert.deepEqual(paths(outer.merged), ['deep.txt', 'mine.txt'])
  assert.equal(read(dir, 'deep.txt'), 'child\n')
  assert.equal((await worktree.removeCopy(child, root)).removed, true)
  assert.equal((await worktree.removeCopy(parent, root)).removed, true)
  assert.equal(git(dir, 'worktree', 'list').split('\n').length, 1)
})

test('removing a copy saves what was never merged as a patch and refuses anything outside the worktrees folder', async t => {
  const dir = repo(t)
  put(dir, { 'node_modules/pkg.js': 'module\n' })
  const { copy, root } = await copyOf(t, dir)
  put(copy.workspace, { 'unmerged.txt': 'work in progress\n', 'a.txt': 'one\nchanged\nthree\n' })
  const outside = folder(t, 'outside')
  put(outside, { 'precious.txt': 'x' })
  const strayLink = path.join(outside, 'stray')
  fs.symlinkSync(path.join(dir, 'node_modules'), strayLink, process.platform === 'win32' ? 'junction' : 'dir')
  const refused = await worktree.removeCopy({ ...copy, dir: outside }, root)
  assert.equal(refused.removed, false)
  assert.match(refused.error, /is not below/)
  assert.equal(read(outside, 'precious.txt'), 'x')
  // A link recorded outside the copy is not the copy's to remove.
  const removed = await worktree.removeCopy({ ...copy, links: [...copy.links, strayLink] }, root, 'run-test')
  assert.equal(removed.removed, true)
  assert.ok(fs.lstatSync(strayLink).isSymbolicLink(), 'a link outside the copy is left')
  assert.ok(removed.patch.startsWith(path.join(root, 'patches')), 'the patch is kept beside the copies')
  const patch = fs.readFileSync(removed.patch, 'utf8')
  assert.match(patch, /unmerged\.txt/)
  assert.match(patch, /\+work in progress/)
  assert.match(patch, /\+changed/)
  git(dir, 'apply', removed.patch)
  assert.equal(read(dir, 'unmerged.txt'), 'work in progress\n', 'the patch applies to the original')
  assert.equal(fs.existsSync(copy.dir), false)
  assert.equal(read(dir, 'node_modules/pkg.js'), 'module\n')
  assert.deepEqual(fs.readdirSync(root), ['patches'])
})

test('removing a copy never deletes what a link in it leads to, even a link Orbit did not make or failed to unlink', async t => {
  // git for Windows' `worktree remove --force` follows a junction and empties its target (seen with git 2.24): the
  // source's node_modules. The copy goes by Node's rm instead, which unlinks links rather than following them.
  const dir = repo(t)
  put(dir, { 'node_modules/pkg.js': 'module\n' })
  const { copy, root } = await copyOf(t, dir)
  fs.mkdirSync(path.join(copy.workspace, 'sub'), { recursive: true })
  fs.symlinkSync(path.join(dir, 'node_modules'), path.join(copy.workspace, 'sub', 'deps'), process.platform === 'win32' ? 'junction' : 'dir')
  // `links: []`: Orbit's own node_modules link is still in the copy, as if unlinking it first had failed.
  const removed = await worktree.removeCopy({ ...copy, links: [] }, root, 'run-test')
  assert.equal(removed.removed, true, removed.error)
  assert.equal(fs.existsSync(copy.dir), false)
  assert.equal(read(dir, 'node_modules/pkg.js'), 'module\n', 'the source\'s node_modules is untouched')
  assert.match(git(dir, 'worktree', 'list'), /^[^\n]*$/, 'git lists no worktree but the original')
})

test('copies of runs that no longer exist are swept at start: unmerged work saved first, a live owner\'s left alone', async t => {
  const dir = repo(t)
  const { copy, root } = await copyOf(t, dir)
  put(copy.workspace, { 'left.txt': 'unfinished\n' })
  const meta = JSON.parse(fs.readFileSync(copy.meta, 'utf8'))
  fs.writeFileSync(copy.meta, JSON.stringify({ ...meta, pid: process.ppid }))
  const alive = await worktree.sweepLeftovers(root)
  assert.deepEqual([alive.removed, alive.kept.length], [0, 1], 'the process that owns the folder still lives')
  assert.ok(fs.existsSync(copy.dir))
  fs.writeFileSync(copy.meta, '{ not json')
  assert.equal((await worktree.sweepLeftovers(root)).removed, 0, 'what cannot be read is not known to be ours')
  assert.ok(fs.existsSync(copy.dir))
  fs.writeFileSync(copy.meta, JSON.stringify({ ...meta, pid: 2147483000 }))
  const swept = await worktree.sweepLeftovers(root)
  assert.equal(swept.removed, 1)
  assert.equal(swept.patches.length, 1)
  assert.match(fs.readFileSync(swept.patches[0], 'utf8'), /\+unfinished/)
  assert.equal(fs.existsSync(copy.dir), false)
  assert.equal(git(dir, 'worktree', 'list').split('\n').length, 1)
})
