// Isolated copies of a workspace (electron/agent-worktree.mts): a copy starts from the parent's current state without
// touching it, a finished helper's changes merge into the target file by file (conflicts leave the target alone), nested
// copies work, and removing a copy never follows its links. Everything runs against real temporary git repositories.
// The tests are spread over agent-worktree*.test.cjs, which run side by side (the fixtures are in helpers-worktree.cjs).
// This part merges a finished helper's changes back: added, modified and deleted files, line by line, a follow-up merge, a
// CRLF working tree, and the merge report.
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const worktree = require('../electron/agent-worktree.mts')
const { git, crlf, put, read, repo, copyOf, paths } = require('./helpers-worktree.cjs')

test('a finished helper\'s changes merge into the target: modified, added and deleted files', async t => {
  const dir = repo(t, { 'a.txt': 'one\ntwo\nthree\n', 'b.txt': 'bee\n', 'keep.txt': 'keep\n' })
  const { copy, root } = await copyOf(t, dir)
  const head = git(dir, 'rev-parse', 'HEAD')
  put(copy.workspace, { 'a.txt': 'one\n2\nthree\n', 'sub/c.txt': 'new file\n' })
  fs.rmSync(path.join(copy.workspace, 'b.txt'))
  const result = await worktree.mergeCopy(copy)
  assert.equal(result.ok, true)
  assert.deepEqual(result.merged.map(file => [file.path, file.kind]).sort(), [['a.txt', 'modify'], ['b.txt', 'delete'], ['sub/c.txt', 'create']])
  assert.deepEqual(result.conflicts, [])
  assert.equal(read(dir, 'a.txt'), 'one\n2\nthree\n')
  assert.equal(read(dir, 'sub/c.txt'), 'new file\n')
  assert.equal(fs.existsSync(path.join(dir, 'b.txt')), false)
  assert.equal(read(dir, 'keep.txt'), 'keep\n', 'a file the helper did not touch stays')
  const modified = result.merged.find(file => file.path === 'a.txt')
  assert.deepEqual([modified.before, modified.after], ['one\ntwo\nthree\n', 'one\n2\nthree\n'], 'the texts for the change record')
  assert.equal(result.merged.find(file => file.path === 'sub/c.txt').before, null)
  assert.equal(result.merged.find(file => file.path === 'b.txt').after, null)
  assert.equal(git(dir, 'diff', '--cached', '--name-only'), '', 'the merge stages nothing in the target')
  assert.equal(git(dir, 'rev-parse', 'HEAD'), head)
  const report = worktree.describeMerge(copy, result)
  assert.match(report, /MERGED into .*: 3 file\(s\) \(created: sub\/c\.txt; modified: a\.txt; deleted: b\.txt\)/)
  assert.doesNotMatch(report, /CONFLICTS/)
  assert.equal((await worktree.removeCopy(copy, root)).patch, null)
})

test('a file both sides changed in different places is merged line by line', async t => {
  const dir = repo(t, { 'a.txt': 'l1\nl2\nl3\nl4\nl5\n' })
  const { copy } = await copyOf(t, dir)
  put(dir, { 'a.txt': 'T1\nl2\nl3\nl4\nl5\n' })
  put(copy.workspace, { 'a.txt': 'l1\nl2\nl3\nl4\nH5\n' })
  const result = await worktree.mergeCopy(copy)
  assert.deepEqual(result.conflicts, [])
  assert.deepEqual(result.merged.map(file => file.kind), ['modify'])
  assert.equal(read(dir, 'a.txt'), 'T1\nl2\nl3\nl4\nH5\n')
})

test('a second merge after a follow-up applies only what is new and keeps the target\'s own edits', async t => {
  const dir = repo(t, { 'a.txt': 'l1\nl2\nl3\nl4\nl5\nl6\n' })
  const { copy } = await copyOf(t, dir)
  put(copy.workspace, { 'a.txt': 'l1\nH2\nl3\nl4\nl5\nl6\n' })
  const first = await worktree.mergeCopy(copy)
  assert.equal(first.merged.length, 1)
  const again = await worktree.mergeCopy(copy)
  assert.deepEqual([again.merged.length, again.conflicts.length, again.identical], [0, 0, 0], 'nothing is merged twice')
  put(dir, { 'a.txt': 'l1\nH2\nl3\nl4\nl5\nT6\n' })
  put(copy.workspace, { 'a.txt': 'l1\nH2\nl3\nH4\nl5\nl6\n' })
  const second = await worktree.mergeCopy(copy)
  assert.deepEqual(second.conflicts, [])
  assert.deepEqual(second.merged.map(file => file.path), ['a.txt'])
  assert.equal(read(dir, 'a.txt'), 'l1\nH2\nl3\nH4\nl5\nT6\n', 'the follow-up\'s change lands on top of the target\'s own edit and the first merge')
  assert.notEqual(copy.base, copy.startBase, 'the copy\'s base moved up with what merged')
})

test('line endings are not changes: a CRLF working tree merges line by line and keeps its endings', async t => {
  const dir = repo(t, { 'a.txt': crlf('l1\nl2\nl3\nl4\nl5\n'), 'b.txt': crlf('b1\nb2\n'), 'c.txt': crlf('c\n') }, { eol: true })
  const { copy } = await copyOf(t, dir)
  assert.ok(read(copy.workspace, 'a.txt').includes('\r\n'), 'the copy is checked out with the repository\'s line endings')
  put(dir, { 'a.txt': crlf('T1\nl2\nl3\nl4\nl5\n') })
  put(copy.workspace, { 'a.txt': crlf('l1\nl2\nl3\nl4\nH5\n'), 'c.txt': crlf('c edited\n') })
  fs.rmSync(path.join(copy.workspace, 'b.txt'))
  const result = await worktree.mergeCopy(copy)
  assert.deepEqual(result.conflicts, [], 'an unchanged CRLF file is recognised as unchanged (b.txt deletes cleanly)')
  assert.deepEqual(paths(result.merged), ['a.txt', 'b.txt', 'c.txt'])
  assert.equal(read(dir, 'a.txt'), crlf('T1\nl2\nl3\nl4\nH5\n'), 'the merged file keeps the target\'s CRLF')
  assert.equal(read(dir, 'c.txt'), crlf('c edited\n'))
  assert.equal(fs.existsSync(path.join(dir, 'b.txt')), false)
})

test('the merge report stays short however many files conflict, and says so when there is nothing to merge', () => {
  const copy = { dir: path.join(os.tmpdir(), 'copy'), workspace: path.join(os.tmpdir(), 'copy'), sourceTop: path.join(os.tmpdir(), 'top'), target: path.join(os.tmpdir(), 'top'), base: 'a'.repeat(40) }
  const conflicts = Array.from({ length: 30 }, (_, index) => ({ path: `f${index}.txt`, reason: 'changed on both sides and the changes overlap' }))
  const text = worktree.describeMerge(copy, { ok: true, merged: [], conflicts, identical: 0 })
  assert.ok(text.length < 4000, `${text.length} characters`)
  assert.match(text, /30 file\(s\) were NOT merged/)
  assert.match(text, /and 24 more: f6\.txt/)
  assert.match(worktree.describeMerge(copy, { ok: true, merged: [], conflicts: [], identical: 0 }), /nothing to merge/)
  const many = Array.from({ length: 20 }, (_, index) => ({ path: `m${index}.txt`, kind: 'modify' }))
  assert.match(worktree.describeMerge(copy, { ok: true, merged: many, conflicts: [], identical: 3 }), /20 file\(s\) \(modified: m0\.txt, .*m7\.txt, and 12 more\)/)
})
