// Isolated copies of a workspace (electron/agent-worktree.mts): a copy starts from the parent's current state without
// touching it, a finished helper's changes merge into the target file by file (conflicts leave the target alone), nested
// copies work, and removing a copy never follows its links. Everything runs against real temporary git repositories.
// The tests are spread over agent-worktree*.test.cjs, which run side by side (the fixtures are in helpers-worktree.cjs).
// This part is about merges that do not go through: conflicts (a file both sides changed, created or deleted differently,
// and a binary file; the target is never overwritten) and a target that is gone.
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const worktree = require('../electron/agent-worktree.mts')
const { git, put, read, repo, copyOf } = require('./helpers-worktree.cjs')

test('a conflict leaves the target\'s file untouched, names both versions, and is tried again next time', async t => {
  const dir = repo(t, { 'a.txt': 'l1\nl2\nl3\n', 'other.txt': 'o\n' })
  const { copy } = await copyOf(t, dir)
  put(dir, { 'a.txt': 'l1\nTARGET\nl3\n' })
  put(copy.workspace, { 'a.txt': 'l1\nHELPER\nl3\n', 'other.txt': 'o changed\n' })
  const first = await worktree.mergeCopy(copy)
  assert.deepEqual(first.conflicts.map(conflict => conflict.path), ['a.txt'])
  assert.match(first.conflicts[0].reason, /overlap/)
  assert.equal(read(dir, 'a.txt'), 'l1\nTARGET\nl3\n', 'the target\'s file is untouched')
  assert.equal(read(dir, 'other.txt'), 'o changed\n', 'what merges cleanly is merged')
  const report = worktree.describeMerge(copy, first)
  assert.match(report, /CONFLICTS: 1 file\(s\) were NOT merged/)
  assert.ok(report.includes(path.join(copy.dir, 'a.txt')) && report.includes(path.join(dir, 'a.txt')), 'both versions are named')
  const command = /git -C "([^"]+)" diff ([0-9a-f]{7}) -- "([^"]+)"/.exec(report)
  assert.ok(command, 'the report says how to see what the helper changed')
  const shown = git(command[1], 'diff', command[2], '--', command[3])
  assert.match(shown, /-l2/)
  assert.match(shown, /\+HELPER/)
  const origin = /git -C "([^"]+)" show ([0-9a-f]{7}):(\S+)/.exec(report)
  assert.equal(git(origin[1], 'show', `${origin[2]}:${origin[3]}`), 'l1\nl2\nl3', 'and the version both started from')
  const second = await worktree.mergeCopy(copy)
  assert.deepEqual([second.merged.length, second.conflicts.map(conflict => conflict.path)], [0, ['a.txt']], 'a conflicting path is retried')
  put(dir, { 'a.txt': 'l1\nHELPER\nl3\n' })
  const third = await worktree.mergeCopy(copy)
  assert.deepEqual([third.conflicts.length, third.identical], [0, 1], 'once the target has the helper\'s version the conflict is gone')
})

test('creating or deleting a file on both sides differently is a conflict; the same result on both sides is not', async t => {
  const dir = repo(t, { 'a.txt': 'a\n', 'del.txt': 'to delete\n', 'gone.txt': 'gone\n', 'same.txt': 's\n' })
  const { copy } = await copyOf(t, dir)
  put(copy.workspace, { 'n.txt': 'helper\n', 'gone.txt': 'helper edit\n', 'twin.txt': 'twin\n' })
  fs.rmSync(path.join(copy.workspace, 'del.txt')); fs.rmSync(path.join(copy.workspace, 'same.txt'))
  put(dir, { 'n.txt': 'target\n', 'del.txt': 'target edit\n', 'twin.txt': 'twin\n' })
  fs.rmSync(path.join(dir, 'gone.txt')); fs.rmSync(path.join(dir, 'same.txt'))
  const result = await worktree.mergeCopy(copy)
  const reasons = Object.fromEntries(result.conflicts.map(conflict => [conflict.path, conflict.reason]))
  assert.deepEqual(Object.keys(reasons).sort(), ['del.txt', 'gone.txt', 'n.txt'])
  assert.match(reasons['n.txt'], /created by the helper and, differently, in the target/)
  assert.match(reasons['del.txt'], /deleted by the helper, but changed in the target/)
  assert.match(reasons['gone.txt'], /deleted in the target, but changed by the helper/)
  assert.equal(result.identical, 2, 'a twin file and a file deleted on both sides need nothing')
  assert.deepEqual(result.merged, [])
  assert.equal(read(dir, 'n.txt'), 'target\n')
  assert.equal(read(dir, 'del.txt'), 'target edit\n')
  assert.equal(fs.existsSync(path.join(dir, 'gone.txt')), false)
})

test('a binary file changed on both sides is a conflict, not a text merge', async t => {
  const dir = repo(t, {})
  fs.writeFileSync(path.join(dir, 'img.bin'), Buffer.from([0, 1, 2, 3]))
  git(dir, 'add', '-A'); git(dir, 'commit', '-qm', 'binary')
  const { copy } = await copyOf(t, dir)
  fs.writeFileSync(path.join(copy.workspace, 'img.bin'), Buffer.from([0, 1, 2, 9]))
  fs.writeFileSync(path.join(dir, 'img.bin'), Buffer.from([0, 1, 7, 3]))
  const result = await worktree.mergeCopy(copy)
  assert.match(result.conflicts[0].reason, /binary/)
  assert.deepEqual([...fs.readFileSync(path.join(dir, 'img.bin'))], [0, 1, 7, 3])
  // Changed only by the helper, a binary file is copied.
  fs.writeFileSync(path.join(dir, 'img.bin'), Buffer.from([0, 1, 2, 3]))
  const once = await worktree.mergeCopy(copy)
  assert.deepEqual(once.merged.map(file => [file.path, file.before, file.after]), [['img.bin', undefined, undefined]])
  assert.deepEqual([...fs.readFileSync(path.join(dir, 'img.bin'))], [0, 1, 2, 9])
})

test('a merge whose target is gone fails with a message and merges nothing', async t => {
  const dir = repo(t)
  const { copy } = await copyOf(t, dir)
  put(copy.workspace, { 'x.txt': 'x\n' })
  const moved = `${dir}-moved`
  fs.renameSync(dir, moved)
  t.after(() => fs.rmSync(moved, { recursive: true, force: true }))
  const result = await worktree.mergeCopy(copy)
  assert.equal(result.ok, false)
  assert.match(result.error, /no longer exists/)
  assert.deepEqual([result.merged, result.conflicts], [[], []])
  assert.match(worktree.describeMerge(copy, result), /MERGE FAILED/)
})
