// @ts-check
// GENERATED by scripts/gen-ipc-types.cjs from electron/ipc-contract.cjs; do not edit by hand.
// The preload runs in Electron's renderer sandbox, whose require() only loads Electron's own modules, so the contract
// table is inlined here instead of required. tests/ipc-contract.test.cjs fails when this file drifts from the contract.
const { contextBridge, ipcRenderer } = require('electron')

// [method, channel, arity]: a call forwards at most `arity` arguments (an extra one, such as the DOM event an onClick
// passes, would fail structured cloning). A subscription forwards the payload and returns its unsubscribe function.
/** @type {[method: string, channel: string, arity: number][]} */
const CALLS = [
  ['pickWorkspace', 'workspace:pick', 0],
  ['inspectWorkspace', 'workspace:inspect', 1],
  ['cloneWorkspace', 'workspace:clone', 1],
  ['startTask', 'runtime:start', 1],
  ['stopTask', 'runtime:stop', 1],
  ['pauseAgent', 'runtime:pause', 2],
  ['resumeAgent', 'runtime:resume', 2],
  ['stopAgent', 'runtime:stop-agent', 2],
  ['listRuns', 'runtime:list', 0],
  ['getRun', 'runtime:get', 1],
  ['getRunChanges', 'runtime:changes', 1],
  ['readTraceImage', 'runtime:image', 2],
  ['messageAgent', 'runtime:message', 4],
  ['saveAttachments', 'attachments:save', 2],
  ['readAttachmentImage', 'attachments:image', 1],
  ['discardAttachments', 'attachments:discard', 2],
  ['loadState', 'state:load', 0],
  ['saveState', 'state:save', 1],
  ['projectIndexStatus', 'project-index:status', 2],
  ['listMemory', 'memory:list', 2],
  ['saveMemory', 'memory:save', 1],
  ['removeMemory', 'memory:remove', 3],
  ['pinMemory', 'memory:pin', 4],
  ['setMemorySharing', 'memory:sharing', 2],
  ['forgetChatMemory', 'memory:forget-chat', 2],
  ['memoryStats', 'memory:stats', 2],
  ['listCapabilities', 'capabilities:list', 1],
  ['pinCapability', 'capabilities:pin', 3],
  ['setCapabilityEnabled', 'capabilities:enable', 3],
  ['setCapabilityParams', 'capabilities:params', 3],
  ['readCapability', 'capabilities:read', 2],
  ['installCapability', 'capabilities:install', 1],
  ['removeCapability', 'capabilities:remove', 2],
  ['restoreCapability', 'capabilities:restore', 3],
  ['checkProviders', 'providers:health', 1],
  ['getQuotas', 'quota:get', 2],
  ['applyArtifact', 'artifact:apply', 1],
  ['openExternal', 'shell:open', 1],
  ['openPath', 'shell:open-path', 1],
  ['ping', 'app:ping', 0],
  ['relaunch', 'app:relaunch', 0],
  ['setFullScreen', 'app:fullscreen', 1],
  ['restartRuntime', 'runtime:restart', 0],
  ['getRuntimeStatus', 'runtime:status', 0],
]
/** @type {[method: string, channel: string][]} */
const EVENTS = [
  ['onQuotaUpdate', 'quota:update'],
  ['onRuntimeEvent', 'runtime:event'],
  ['onRestartNotice', 'restart:notice'],
  ['onRuntimeStatus', 'runtime:status-changed'],
]

/** @type {Record<string, (...params: any[]) => unknown>} */
const orbit = {}
for (const [method, channel, arity] of CALLS) orbit[method] = (...params) => ipcRenderer.invoke(channel, ...params.slice(0, arity))
for (const [method, channel] of EVENTS) {
  orbit[method] = (handler) => {
    /** @type {(event: import('electron').IpcRendererEvent, payload: unknown) => void} */
    const listener = (_event, payload) => handler(payload)
    ipcRenderer.on(channel, listener)
    return () => ipcRenderer.removeListener(channel, listener)
  }
}
contextBridge.exposeInMainWorld('orbit', orbit)
